//! SSP (Salto Security Protocol) Layer
//!
//! Implements the secure communication protocol between phone and lock:
//! - Two-step challenge-response authentication
//! - Session-based encryption with chained IV management
//! - CRC-16 integrity verification
//! - State machine controlling protocol flow

use crate::crypto::{
    apply_padding, crc16_ssp, decrypt_aes_cbc, derive_session_key, encrypt_aes_cbc, remove_padding,
    rotate_right,
};
use crate::error::Error;
use crate::security::random::{OsRandom, RandomSource};

/// SSP OpCodes for control packets
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum OpCode {
    /// Error response (Lock → Phone)
    Error = 0x00,
    /// Start authentication (both directions)
    OpenSessionStep1 = 0x01,
    /// Complete authentication (both directions)
    OpenSessionStep2 = 0x02,
    /// Update session key (both directions)
    SetKeyValue = 0x03,
    /// Query SSP version (both directions)
    GetVersion = 0x04,
}

impl TryFrom<u8> for OpCode {
    type Error = Error;

    fn try_from(value: u8) -> Result<Self, <Self as TryFrom<u8>>::Error> {
        match value {
            0x00 => Ok(OpCode::Error),
            0x01 => Ok(OpCode::OpenSessionStep1),
            0x02 => Ok(OpCode::OpenSessionStep2),
            0x03 => Ok(OpCode::SetKeyValue),
            0x04 => Ok(OpCode::GetVersion),
            _ => Err(Error::InvalidData(format!(
                "Unknown OpCode: 0x{:02X}",
                value
            ))),
        }
    }
}

/// Control byte flags
pub mod control {
    /// Request flag: 1 = Control packet (OpCode follows), 0 = Data packet
    pub const REQUEST_FLAG: u8 = 0x01;
    /// Encrypted flag: 0 = Unencrypted, 1 = Encrypted
    pub const ENCRYPTED_FLAG: u8 = 0x02;

    /// Unencrypted control packet header (0x01)
    pub const UNENCRYPTED_CONTROL: u8 = REQUEST_FLAG;
    /// Encrypted control packet header (0x03)
    pub const ENCRYPTED_CONTROL: u8 = REQUEST_FLAG | ENCRYPTED_FLAG;
    /// Encrypted data packet header (0x02)
    pub const ENCRYPTED_DATA: u8 = ENCRYPTED_FLAG;
}

/// SSP protocol state machine states
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SspState {
    /// Initial state - waiting for authentication
    Ready,
    /// Step 1 completed - phone sent RandomB, waiting for Step 2
    AuthStep1,
    /// Authentication complete - session key established
    InSession,
}

impl std::fmt::Display for SspState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SspState::Ready => write!(f, "READY"),
            SspState::AuthStep1 => write!(f, "AUTH_STEP_1"),
            SspState::InSession => write!(f, "IN_SESSION"),
        }
    }
}

/// SSP protocol version
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SspVersion {
    pub major: u8,
    pub minor: u8,
}

impl Default for SspVersion {
    fn default() -> Self {
        Self { major: 1, minor: 0 }
    }
}

/// Secure Protocol Manager - handles SSP layer communication
///
/// Manages the SSP state machine, encryption/decryption, and IV chaining.
pub struct SecureProtocolManager {
    /// Current protocol state
    state: SspState,
    /// Current IV for AES-CBC (chained across messages)
    iv: [u8; 16],
    /// Pre-shared key from MobileKey (kN)
    kn_key: [u8; 16],
    /// Derived session key (set after successful authentication)
    session_key: Option<[u8; 16]>,
    /// RandomB generated by phone during Step 1
    random_b: Option<[u8; 16]>,
    /// RandomA received from lock during Step 2
    random_a: Option<[u8; 16]>,
    /// Protocol version
    version: SspVersion,
    /// Source of the 16-byte `RandomB` challenge generated during Step 1
    random: Box<dyn RandomSource + Send>,
}

impl SecureProtocolManager {
    /// Create a new SecureProtocolManager with the given kN key.
    ///
    /// Uses the operating-system CSPRNG for the `RandomB` challenge.
    pub fn new(kn_key: [u8; 16]) -> Self {
        Self::with_random(kn_key, Box::new(OsRandom))
    }

    /// Create a new SecureProtocolManager with an injected random source.
    ///
    /// Used by tests and fixture generation to make the handshake deterministic
    /// (see [`crate::security::random::FixedRandom`]).
    pub fn with_random(kn_key: [u8; 16], random: Box<dyn RandomSource + Send>) -> Self {
        Self {
            state: SspState::Ready,
            iv: [0u8; 16], // Initial IV is all zeros
            kn_key,
            session_key: None,
            random_b: None,
            random_a: None,
            version: SspVersion::default(),
            random,
        }
    }

    /// Get current protocol state
    pub fn state(&self) -> SspState {
        self.state
    }

    /// Get protocol version
    pub fn version(&self) -> SspVersion {
        self.version
    }

    /// Check if session is established
    pub fn is_in_session(&self) -> bool {
        self.state == SspState::InSession
    }

    /// Get session key (only available after authentication)
    pub fn session_key(&self) -> Option<&[u8; 16]> {
        self.session_key.as_ref()
    }

    /// `RandomB` generated by this side during OpenSessionStep1.
    pub fn random_b(&self) -> Option<&[u8; 16]> {
        self.random_b.as_ref()
    }

    /// `RandomA` received from the lock during OpenSessionStep2.
    pub fn random_a(&self) -> Option<&[u8; 16]> {
        self.random_a.as_ref()
    }

    /// Current AES-CBC IV (chained across every encrypt and decrypt).
    pub fn iv(&self) -> &[u8; 16] {
        &self.iv
    }

    /// Pre-shared key (kN) taken from the MobileKey.
    pub fn kn_key(&self) -> &[u8; 16] {
        &self.kn_key
    }

    /// Reset the protocol to initial state
    pub fn reset(&mut self) {
        self.state = SspState::Ready;
        self.iv = [0u8; 16];
        self.session_key = None;
        self.random_b = None;
        self.random_a = None;
    }

    pub fn process_packet(&mut self, packet: &[u8]) -> Result<Vec<u8>, Error> {
        if packet.len() < 2 {
            return Err(Error::InvalidData("SSP packet too short".to_string()));
        }

        let control_byte = packet[0];
        let is_encrypted = (control_byte & control::ENCRYPTED_FLAG) != 0;
        let is_control = (control_byte & control::REQUEST_FLAG) != 0;

        let payload = if is_encrypted {
            self.decrypt_payload(&packet[1..])?
        } else {
            packet[1..].to_vec()
        };

        if is_control {
            self.process_control_packet(&payload, is_encrypted)
        } else {
            self.process_data_packet(&payload)
        }
    }

    /// Process a control packet (OpCode-based)
    fn process_control_packet(
        &mut self,
        payload: &[u8],
        was_encrypted: bool,
    ) -> Result<Vec<u8>, Error> {
        if payload.is_empty() {
            return Err(Error::InvalidData("Empty control packet".to_string()));
        }

        let opcode = OpCode::try_from(payload[0])?;

        match opcode {
            OpCode::Error => Err(Error::InvalidData(
                "Received SSPError control packet".to_string(),
            )),
            OpCode::OpenSessionStep1 => {
                self.handle_open_session_step1(&payload[1..], was_encrypted)
            }
            OpCode::OpenSessionStep2 => {
                self.handle_open_session_step2(&payload[1..], was_encrypted)
            }
            OpCode::SetKeyValue => self.handle_set_key_value(&payload[1..]),
            OpCode::GetVersion => self.handle_get_version(),
        }
    }

    /// Process a data packet (application layer passthrough)
    fn process_data_packet(&mut self, payload: &[u8]) -> Result<Vec<u8>, Error> {
        if self.state != SspState::InSession {
            return Err(Error::InvalidState {
                expected: "IN_SESSION".to_string(),
                actual: self.state.to_string(),
            });
        }

        Ok(payload.to_vec())
    }

    fn handle_open_session_step1(
        &mut self,
        _payload: &[u8],
        was_encrypted: bool,
    ) -> Result<Vec<u8>, Error> {
        if was_encrypted {
            return Err(Error::InvalidData(
                "OpenSessionStep1 request should not be encrypted".to_string(),
            ));
        }

        if self.state != SspState::Ready {
            return Err(Error::InvalidState {
                expected: "READY".to_string(),
                actual: self.state.to_string(),
            });
        }

        let random_b = self.random.random16();
        self.random_b = Some(random_b);

        let mut response_data = Vec::with_capacity(17);
        response_data.push(OpCode::OpenSessionStep1 as u8);
        response_data.extend_from_slice(&random_b);

        let encrypted_response = self.encrypt_payload(&response_data)?;
        self.state = SspState::AuthStep1;

        let mut packet = Vec::with_capacity(1 + encrypted_response.len());
        packet.push(control::ENCRYPTED_CONTROL);
        packet.extend_from_slice(&encrypted_response);

        Ok(packet)
    }

    fn handle_open_session_step2(
        &mut self,
        payload: &[u8],
        was_encrypted: bool,
    ) -> Result<Vec<u8>, Error> {
        if !was_encrypted {
            return Err(Error::InvalidData(
                "OpenSessionStep2 request must be encrypted".to_string(),
            ));
        }

        if self.state != SspState::AuthStep1 {
            return Err(Error::InvalidState {
                expected: "AUTH_STEP_1".to_string(),
                actual: self.state.to_string(),
            });
        }

        if payload.len() < 32 {
            return Err(Error::InvalidData(format!(
                "OpenSessionStep2 payload too short: expected 32 bytes, got {}",
                payload.len()
            )));
        }

        let mut random_a = [0u8; 16];
        let mut random_b_prime = [0u8; 16];
        random_a.copy_from_slice(&payload[0..16]);
        random_b_prime.copy_from_slice(&payload[16..32]);

        let stored_random_b = self.random_b.ok_or_else(|| Error::InvalidState {
            expected: "RandomB stored".to_string(),
            actual: "RandomB not found".to_string(),
        })?;

        let expected_random_b_prime = rotate_right(&stored_random_b);

        if random_b_prime[..] != expected_random_b_prime[..] {
            self.state = SspState::Ready;
            return Err(Error::AuthenticationFailed);
        }

        self.random_a = Some(random_a);
        let random_a_prime = rotate_right(&random_a);

        let mut response_data = Vec::with_capacity(17);
        response_data.push(OpCode::OpenSessionStep2 as u8);
        response_data.extend_from_slice(&random_a_prime);

        let encrypted_response = self.encrypt_payload(&response_data)?;

        let session_key = derive_session_key(&random_a, &stored_random_b);
        self.session_key = Some(session_key);
        self.state = SspState::InSession;

        let mut packet = Vec::with_capacity(1 + encrypted_response.len());
        packet.push(control::ENCRYPTED_CONTROL);
        packet.extend_from_slice(&encrypted_response);

        Ok(packet)
    }

    fn handle_set_key_value(&mut self, payload: &[u8]) -> Result<Vec<u8>, Error> {
        if self.state != SspState::InSession {
            return Err(Error::InvalidState {
                expected: "IN_SESSION".to_string(),
                actual: self.state.to_string(),
            });
        }

        if payload.len() < 17 {
            return Err(Error::InvalidData(format!(
                "SetKeyValue payload too short: expected 17 bytes, got {}",
                payload.len()
            )));
        }

        let mut new_key = [0u8; 16];
        new_key.copy_from_slice(&payload[1..17]);
        self.session_key = Some(new_key);

        let response_data = vec![OpCode::SetKeyValue as u8];
        let encrypted_response = self.encrypt_payload(&response_data)?;

        let mut packet = Vec::with_capacity(1 + encrypted_response.len());
        packet.push(control::ENCRYPTED_CONTROL);
        packet.extend_from_slice(&encrypted_response);

        Ok(packet)
    }

    fn handle_get_version(&self) -> Result<Vec<u8>, Error> {
        Ok(vec![
            control::UNENCRYPTED_CONTROL,
            OpCode::GetVersion as u8,
            self.version.major,
            self.version.minor,
        ])
    }

    fn encrypt_payload(&mut self, data: &[u8]) -> Result<Vec<u8>, Error> {
        let crc = crc16_ssp(data);

        let mut plaintext = Vec::with_capacity(data.len() + 2);
        plaintext.extend_from_slice(data);
        plaintext.extend_from_slice(&crc);

        let padded = apply_padding(&plaintext);
        let key = self.current_encryption_key();
        let ciphertext = encrypt_aes_cbc(&key, &self.iv, &padded);

        self.update_iv_from_ciphertext(&ciphertext);

        Ok(ciphertext)
    }

    fn decrypt_payload(&mut self, ciphertext: &[u8]) -> Result<Vec<u8>, Error> {
        if ciphertext.len() < 16 || !ciphertext.len().is_multiple_of(16) {
            return Err(Error::InvalidData(format!(
                "Invalid ciphertext length: {} (must be multiple of 16)",
                ciphertext.len()
            )));
        }

        let key = self.current_encryption_key();
        let decrypted = decrypt_aes_cbc(&key, &self.iv, ciphertext)?;

        self.update_iv_from_ciphertext(ciphertext);

        let unpadded = remove_padding(&decrypted)?;
        if unpadded.len() < 2 {
            return Err(Error::InvalidData(
                "Decrypted data too short for CRC".to_string(),
            ));
        }

        let data = &unpadded[..unpadded.len() - 2];
        let received_crc = &unpadded[unpadded.len() - 2..];
        let calculated_crc = crc16_ssp(data);

        if received_crc != calculated_crc {
            return Err(Error::InvalidCrc);
        }

        Ok(data.to_vec())
    }

    fn current_encryption_key(&self) -> [u8; 16] {
        self.session_key.unwrap_or(self.kn_key)
    }

    fn update_iv_from_ciphertext(&mut self, ciphertext: &[u8]) {
        if ciphertext.len() >= 16 {
            self.iv
                .copy_from_slice(&ciphertext[ciphertext.len() - 16..]);
        }
    }

    pub fn build_open_session_step1_request() -> Vec<u8> {
        vec![control::UNENCRYPTED_CONTROL, OpCode::OpenSessionStep1 as u8]
    }

    pub fn build_get_version_request() -> Vec<u8> {
        vec![control::UNENCRYPTED_CONTROL, OpCode::GetVersion as u8]
    }

    pub fn wrap_data(&mut self, data: &[u8]) -> Result<Vec<u8>, Error> {
        if self.state != SspState::InSession {
            return Err(Error::InvalidState {
                expected: "IN_SESSION".to_string(),
                actual: self.state.to_string(),
            });
        }

        let encrypted = self.encrypt_payload(data)?;

        let mut packet = Vec::with_capacity(1 + encrypted.len());
        packet.push(control::ENCRYPTED_DATA);
        packet.extend_from_slice(&encrypted);

        Ok(packet)
    }

    pub fn unwrap_data(&mut self, packet: &[u8]) -> Result<Vec<u8>, Error> {
        if packet.is_empty() {
            return Err(Error::InvalidData("Empty packet".to_string()));
        }

        let control_byte = packet[0];
        if (control_byte & control::ENCRYPTED_FLAG) == 0 {
            return Err(Error::InvalidData("Expected encrypted packet".to_string()));
        }

        self.decrypt_payload(&packet[1..])
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::security::random::FixedRandom;

    const KN: [u8; 16] = [
        0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e,
        0x0f,
    ];
    const RANDOM_B: [u8; 16] = [
        0xb0, 0xb1, 0xb2, 0xb3, 0xb4, 0xb5, 0xb6, 0xb7, 0xb8, 0xb9, 0xba, 0xbb, 0xbc, 0xbd, 0xbe,
        0xbf,
    ];

    fn manager() -> SecureProtocolManager {
        SecureProtocolManager::with_random(KN, Box::new(FixedRandom::single(RANDOM_B)))
    }

    #[test]
    fn opcodes_round_trip_and_reject_unknown_values() {
        for (byte, opcode) in [
            (0x00, OpCode::Error),
            (0x01, OpCode::OpenSessionStep1),
            (0x02, OpCode::OpenSessionStep2),
            (0x03, OpCode::SetKeyValue),
            (0x04, OpCode::GetVersion),
        ] {
            assert_eq!(OpCode::try_from(byte).unwrap(), opcode);
        }
        assert!(matches!(OpCode::try_from(0x05), Err(Error::InvalidData(_))));
    }

    #[test]
    fn a_packet_shorter_than_two_bytes_is_rejected() {
        let mut ssp = manager();
        assert!(matches!(
            ssp.process_packet(&[]),
            Err(Error::InvalidData(_))
        ));
        assert!(matches!(
            ssp.process_packet(&[0x01]),
            Err(Error::InvalidData(_))
        ));
    }

    #[test]
    fn step1_answers_with_an_encrypted_control_packet_and_advances_the_iv() {
        let mut ssp = manager();
        assert_eq!(ssp.state(), SspState::Ready);
        assert_eq!(ssp.iv(), &[0u8; 16]);

        let response = ssp.process_packet(&[0x01, 0x01]).unwrap();
        assert_eq!(response[0], control::ENCRYPTED_CONTROL);
        // [opcode ‖ randomB] = 17 bytes, + 2 CRC + padding = 32.
        assert_eq!(response.len(), 33);
        assert_eq!(ssp.state(), SspState::AuthStep1);
        assert_eq!(ssp.random_b(), Some(&RANDOM_B));
        assert_eq!(ssp.iv()[..], response[response.len() - 16..]);
        assert!(ssp.session_key().is_none());
    }

    #[test]
    fn step1_must_be_unencrypted_and_only_from_the_ready_state() {
        let mut ssp = manager();
        assert!(matches!(
            ssp.process_packet(&[control::ENCRYPTED_CONTROL, 0x01]),
            // Fails while decrypting: 1 byte is not a valid ciphertext.
            Err(Error::InvalidData(_))
        ));

        let mut ssp = manager();
        ssp.process_packet(&[0x01, 0x01]).unwrap();
        assert!(matches!(
            ssp.process_packet(&[0x01, 0x01]),
            Err(Error::InvalidState { .. })
        ));
    }

    #[test]
    fn get_version_is_plaintext_and_changes_nothing() {
        let mut ssp = manager();
        let response = ssp.process_packet(&[0x01, 0x04]).unwrap();
        assert_eq!(response, vec![control::UNENCRYPTED_CONTROL, 0x04, 1, 0]);
        assert_eq!(ssp.state(), SspState::Ready);
        assert_eq!(ssp.iv(), &[0u8; 16]);
    }

    #[test]
    fn an_error_control_packet_is_reported_as_such() {
        let mut ssp = manager();
        match ssp.process_packet(&[0x01, 0x00]) {
            Err(Error::InvalidData(message)) => {
                assert!(message.contains("SSPError"), "{message}")
            }
            other => panic!("unexpected {other:?}"),
        }
    }

    #[test]
    fn data_packets_require_an_established_session() {
        let mut ssp = manager();
        assert!(matches!(
            ssp.process_packet(&[0x00, 0x02, 0x00]),
            Err(Error::InvalidState { .. })
        ));
        assert!(matches!(
            ssp.wrap_data(&[0x00]),
            Err(Error::InvalidState { .. })
        ));
    }

    #[test]
    fn unwrap_data_rejects_a_plaintext_packet() {
        let mut ssp = manager();
        assert!(matches!(ssp.unwrap_data(&[]), Err(Error::InvalidData(_))));
        assert!(matches!(
            ssp.unwrap_data(&[control::UNENCRYPTED_CONTROL, 0x01]),
            Err(Error::InvalidData(_))
        ));
    }

    #[test]
    fn ciphertext_length_must_be_a_positive_multiple_of_sixteen() {
        let mut ssp = manager();
        for len in [1usize, 15, 17, 31] {
            let packet = [vec![control::ENCRYPTED_DATA], vec![0u8; len]].concat();
            assert!(
                matches!(ssp.process_packet(&packet), Err(Error::InvalidData(_))),
                "ciphertext of {len} bytes should be rejected"
            );
        }
    }

    #[test]
    fn reset_clears_the_session_but_keeps_the_kn_key() {
        let mut ssp = manager();
        ssp.process_packet(&[0x01, 0x01]).unwrap();
        ssp.reset();
        assert_eq!(ssp.state(), SspState::Ready);
        assert_eq!(ssp.iv(), &[0u8; 16]);
        assert!(ssp.random_b().is_none());
        assert!(ssp.random_a().is_none());
        assert_eq!(ssp.kn_key(), &KN);
    }

    #[test]
    fn request_builders_produce_plaintext_control_packets() {
        assert_eq!(
            SecureProtocolManager::build_open_session_step1_request(),
            vec![0x01, 0x01]
        );
        assert_eq!(
            SecureProtocolManager::build_get_version_request(),
            vec![0x01, 0x04]
        );
    }

    #[test]
    fn default_ssp_version_is_one_zero() {
        assert_eq!(SspVersion::default(), SspVersion { major: 1, minor: 0 });
        assert_eq!(SspState::Ready.to_string(), "READY");
        assert_eq!(SspState::AuthStep1.to_string(), "AUTH_STEP_1");
        assert_eq!(SspState::InSession.to_string(), "IN_SESSION");
    }
}
