//! SSP (Salto Security Protocol) Layer
//!
//! Implements the secure communication protocol between phone and lock:
//! - Two-step challenge-response authentication
//! - Session-based encryption with chained IV management
//! - CRC-16 integrity verification
//! - State machine controlling protocol flow

use crate::crypto::{
    apply_padding, crc16_ssp, decrypt_aes_cbc, derive_session_key, encrypt_aes_cbc, remove_padding,
    rotate_right,
};
use crate::error::Error;

/// SSP OpCodes for control packets
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum OpCode {
    /// Error response (Lock → Phone)
    Error = 0x00,
    /// Start authentication (both directions)
    OpenSessionStep1 = 0x01,
    /// Complete authentication (both directions)
    OpenSessionStep2 = 0x02,
    /// Update session key (both directions)
    SetKeyValue = 0x03,
    /// Query SSP version (both directions)
    GetVersion = 0x04,
}

impl TryFrom<u8> for OpCode {
    type Error = Error;

    fn try_from(value: u8) -> Result<Self, <Self as TryFrom<u8>>::Error> {
        match value {
            0x00 => Ok(OpCode::Error),
            0x01 => Ok(OpCode::OpenSessionStep1),
            0x02 => Ok(OpCode::OpenSessionStep2),
            0x03 => Ok(OpCode::SetKeyValue),
            0x04 => Ok(OpCode::GetVersion),
            _ => Err(Error::InvalidData(format!(
                "Unknown OpCode: 0x{:02X}",
                value
            ))),
        }
    }
}

/// Control byte flags
pub mod control {
    /// Request flag: 1 = Control packet (OpCode follows), 0 = Data packet
    pub const REQUEST_FLAG: u8 = 0x01;
    /// Encrypted flag: 0 = Unencrypted, 1 = Encrypted
    pub const ENCRYPTED_FLAG: u8 = 0x02;

    /// Unencrypted control packet header (0x01)
    pub const UNENCRYPTED_CONTROL: u8 = REQUEST_FLAG;
    /// Encrypted control packet header (0x03)
    pub const ENCRYPTED_CONTROL: u8 = REQUEST_FLAG | ENCRYPTED_FLAG;
    /// Encrypted data packet header (0x02)
    pub const ENCRYPTED_DATA: u8 = ENCRYPTED_FLAG;
}

/// SSP protocol state machine states
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum SspState {
    /// Initial state - waiting for authentication
    Ready,
    /// Step 1 completed - phone sent RandomB, waiting for Step 2
    AuthStep1,
    /// Authentication complete - session key established
    InSession,
}

impl std::fmt::Display for SspState {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            SspState::Ready => write!(f, "READY"),
            SspState::AuthStep1 => write!(f, "AUTH_STEP_1"),
            SspState::InSession => write!(f, "IN_SESSION"),
        }
    }
}

/// SSP protocol version
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct SspVersion {
    pub major: u8,
    pub minor: u8,
}

impl Default for SspVersion {
    fn default() -> Self {
        Self { major: 1, minor: 0 }
    }
}

/// Secure Protocol Manager - handles SSP layer communication
///
/// Manages the SSP state machine, encryption/decryption, and IV chaining.
pub struct SecureProtocolManager {
    /// Current protocol state
    state: SspState,
    /// Current IV for AES-CBC (chained across messages)
    iv: [u8; 16],
    /// Pre-shared key from MobileKey (kN)
    kn_key: [u8; 16],
    /// Derived session key (set after successful authentication)
    session_key: Option<[u8; 16]>,
    /// RandomB generated by phone during Step 1
    random_b: Option<[u8; 16]>,
    /// RandomA received from lock during Step 2
    random_a: Option<[u8; 16]>,
    /// Protocol version
    version: SspVersion,
}

impl SecureProtocolManager {
    /// Create a new SecureProtocolManager with the given kN key
    pub fn new(kn_key: [u8; 16]) -> Self {
        Self {
            state: SspState::Ready,
            iv: [0u8; 16], // Initial IV is all zeros
            kn_key,
            session_key: None,
            random_b: None,
            random_a: None,
            version: SspVersion::default(),
        }
    }

    /// Get current protocol state
    pub fn state(&self) -> SspState {
        self.state
    }

    /// Get protocol version
    pub fn version(&self) -> SspVersion {
        self.version
    }

    /// Check if session is established
    pub fn is_in_session(&self) -> bool {
        self.state == SspState::InSession
    }

    /// Get session key (only available after authentication)
    pub fn session_key(&self) -> Option<&[u8; 16]> {
        self.session_key.as_ref()
    }

    /// Reset the protocol to initial state
    pub fn reset(&mut self) {
        self.state = SspState::Ready;
        self.iv = [0u8; 16];
        self.session_key = None;
        self.random_b = None;
        self.random_a = None;
    }

    pub fn process_packet(&mut self, packet: &[u8]) -> Result<Vec<u8>, Error> {
        if packet.len() < 2 {
            return Err(Error::InvalidData("SSP packet too short".to_string()));
        }

        let control_byte = packet[0];
        let is_encrypted = (control_byte & control::ENCRYPTED_FLAG) != 0;
        let is_control = (control_byte & control::REQUEST_FLAG) != 0;

        let payload = if is_encrypted {
            self.decrypt_payload(&packet[1..])?
        } else {
            packet[1..].to_vec()
        };

        if is_control {
            self.process_control_packet(&payload, is_encrypted)
        } else {
            self.process_data_packet(&payload)
        }
    }

    /// Process a control packet (OpCode-based)
    fn process_control_packet(
        &mut self,
        payload: &[u8],
        was_encrypted: bool,
    ) -> Result<Vec<u8>, Error> {
        if payload.is_empty() {
            return Err(Error::InvalidData("Empty control packet".to_string()));
        }

        let opcode = OpCode::try_from(payload[0])?;

        match opcode {
            OpCode::Error => Err(Error::InvalidData(
                "Received SSPError control packet".to_string(),
            )),
            OpCode::OpenSessionStep1 => {
                self.handle_open_session_step1(&payload[1..], was_encrypted)
            }
            OpCode::OpenSessionStep2 => {
                self.handle_open_session_step2(&payload[1..], was_encrypted)
            }
            OpCode::SetKeyValue => self.handle_set_key_value(&payload[1..]),
            OpCode::GetVersion => self.handle_get_version(),
        }
    }

    /// Process a data packet (application layer passthrough)
    fn process_data_packet(&mut self, payload: &[u8]) -> Result<Vec<u8>, Error> {
        if self.state != SspState::InSession {
            return Err(Error::InvalidState {
                expected: "IN_SESSION".to_string(),
                actual: self.state.to_string(),
            });
        }

        Ok(payload.to_vec())
    }

    fn handle_open_session_step1(
        &mut self,
        _payload: &[u8],
        was_encrypted: bool,
    ) -> Result<Vec<u8>, Error> {
        if was_encrypted {
            return Err(Error::InvalidData(
                "OpenSessionStep1 request should not be encrypted".to_string(),
            ));
        }

        if self.state != SspState::Ready {
            return Err(Error::InvalidState {
                expected: "READY".to_string(),
                actual: self.state.to_string(),
            });
        }

        let random_b = Self::generate_random_bytes();
        self.random_b = Some(random_b);

        let mut response_data = Vec::with_capacity(17);
        response_data.push(OpCode::OpenSessionStep1 as u8);
        response_data.extend_from_slice(&random_b);

        let encrypted_response = self.encrypt_payload(&response_data)?;
        self.state = SspState::AuthStep1;

        let mut packet = Vec::with_capacity(1 + encrypted_response.len());
        packet.push(control::ENCRYPTED_CONTROL);
        packet.extend_from_slice(&encrypted_response);

        Ok(packet)
    }

    fn handle_open_session_step2(
        &mut self,
        payload: &[u8],
        was_encrypted: bool,
    ) -> Result<Vec<u8>, Error> {
        if !was_encrypted {
            return Err(Error::InvalidData(
                "OpenSessionStep2 request must be encrypted".to_string(),
            ));
        }

        if self.state != SspState::AuthStep1 {
            return Err(Error::InvalidState {
                expected: "AUTH_STEP_1".to_string(),
                actual: self.state.to_string(),
            });
        }

        if payload.len() < 32 {
            return Err(Error::InvalidData(format!(
                "OpenSessionStep2 payload too short: expected 32 bytes, got {}",
                payload.len()
            )));
        }

        let mut random_a = [0u8; 16];
        let mut random_b_prime = [0u8; 16];
        random_a.copy_from_slice(&payload[0..16]);
        random_b_prime.copy_from_slice(&payload[16..32]);

        let stored_random_b = self.random_b.ok_or_else(|| Error::InvalidState {
            expected: "RandomB stored".to_string(),
            actual: "RandomB not found".to_string(),
        })?;

        let expected_random_b_prime = rotate_right(&stored_random_b);

        if random_b_prime[..] != expected_random_b_prime[..] {
            self.state = SspState::Ready;
            return Err(Error::AuthenticationFailed);
        }

        self.random_a = Some(random_a);
        let random_a_prime = rotate_right(&random_a);

        let mut response_data = Vec::with_capacity(17);
        response_data.push(OpCode::OpenSessionStep2 as u8);
        response_data.extend_from_slice(&random_a_prime);

        let encrypted_response = self.encrypt_payload(&response_data)?;

        let session_key = derive_session_key(&random_a, &stored_random_b);
        self.session_key = Some(session_key);
        self.state = SspState::InSession;

        let mut packet = Vec::with_capacity(1 + encrypted_response.len());
        packet.push(control::ENCRYPTED_CONTROL);
        packet.extend_from_slice(&encrypted_response);

        Ok(packet)
    }

    fn handle_set_key_value(&mut self, payload: &[u8]) -> Result<Vec<u8>, Error> {
        if self.state != SspState::InSession {
            return Err(Error::InvalidState {
                expected: "IN_SESSION".to_string(),
                actual: self.state.to_string(),
            });
        }

        if payload.len() < 17 {
            return Err(Error::InvalidData(format!(
                "SetKeyValue payload too short: expected 17 bytes, got {}",
                payload.len()
            )));
        }

        let mut new_key = [0u8; 16];
        new_key.copy_from_slice(&payload[1..17]);
        self.session_key = Some(new_key);

        let response_data = vec![OpCode::SetKeyValue as u8];
        let encrypted_response = self.encrypt_payload(&response_data)?;

        let mut packet = Vec::with_capacity(1 + encrypted_response.len());
        packet.push(control::ENCRYPTED_CONTROL);
        packet.extend_from_slice(&encrypted_response);

        Ok(packet)
    }

    fn handle_get_version(&self) -> Result<Vec<u8>, Error> {
        Ok(vec![
            control::UNENCRYPTED_CONTROL,
            OpCode::GetVersion as u8,
            self.version.major,
            self.version.minor,
        ])
    }

    fn encrypt_payload(&mut self, data: &[u8]) -> Result<Vec<u8>, Error> {
        let crc = crc16_ssp(data);

        let mut plaintext = Vec::with_capacity(data.len() + 2);
        plaintext.extend_from_slice(data);
        plaintext.extend_from_slice(&crc);

        let padded = apply_padding(&plaintext);
        let key = self.current_encryption_key();
        let ciphertext = encrypt_aes_cbc(&key, &self.iv, &padded);

        self.update_iv_from_ciphertext(&ciphertext);

        Ok(ciphertext)
    }

    fn decrypt_payload(&mut self, ciphertext: &[u8]) -> Result<Vec<u8>, Error> {
        if ciphertext.len() < 16 || !ciphertext.len().is_multiple_of(16) {
            return Err(Error::InvalidData(format!(
                "Invalid ciphertext length: {} (must be multiple of 16)",
                ciphertext.len()
            )));
        }

        let key = self.current_encryption_key();
        let decrypted = decrypt_aes_cbc(&key, &self.iv, ciphertext)?;

        self.update_iv_from_ciphertext(ciphertext);

        let unpadded = remove_padding(&decrypted)?;
        if unpadded.len() < 2 {
            return Err(Error::InvalidData(
                "Decrypted data too short for CRC".to_string(),
            ));
        }

        let data = &unpadded[..unpadded.len() - 2];
        let received_crc = &unpadded[unpadded.len() - 2..];
        let calculated_crc = crc16_ssp(data);

        if received_crc != calculated_crc {
            return Err(Error::InvalidCrc);
        }

        Ok(data.to_vec())
    }

    fn current_encryption_key(&self) -> [u8; 16] {
        self.session_key.unwrap_or(self.kn_key)
    }

    fn update_iv_from_ciphertext(&mut self, ciphertext: &[u8]) {
        if ciphertext.len() >= 16 {
            self.iv
                .copy_from_slice(&ciphertext[ciphertext.len() - 16..]);
        }
    }

    fn generate_random_bytes() -> [u8; 16] {
        use std::time::{SystemTime, UNIX_EPOCH};

        // TODO: Use proper cryptographic RNG in production
        let seed = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap_or_default()
            .as_nanos() as u64;

        let mut state = seed;
        let mut result = [0u8; 16];

        for byte in &mut result {
            state ^= state << 13;
            state ^= state >> 7;
            state ^= state << 17;
            *byte = (state & 0xFF) as u8;
        }

        result
    }

    pub fn build_open_session_step1_request() -> Vec<u8> {
        vec![control::UNENCRYPTED_CONTROL, OpCode::OpenSessionStep1 as u8]
    }

    pub fn build_get_version_request() -> Vec<u8> {
        vec![control::UNENCRYPTED_CONTROL, OpCode::GetVersion as u8]
    }

    pub fn wrap_data(&mut self, data: &[u8]) -> Result<Vec<u8>, Error> {
        if self.state != SspState::InSession {
            return Err(Error::InvalidState {
                expected: "IN_SESSION".to_string(),
                actual: self.state.to_string(),
            });
        }

        let encrypted = self.encrypt_payload(data)?;

        let mut packet = Vec::with_capacity(1 + encrypted.len());
        packet.push(control::ENCRYPTED_DATA);
        packet.extend_from_slice(&encrypted);

        Ok(packet)
    }

    pub fn unwrap_data(&mut self, packet: &[u8]) -> Result<Vec<u8>, Error> {
        if packet.is_empty() {
            return Err(Error::InvalidData("Empty packet".to_string()));
        }

        let control_byte = packet[0];
        if (control_byte & control::ENCRYPTED_FLAG) == 0 {
            return Err(Error::InvalidData("Expected encrypted packet".to_string()));
        }

        self.decrypt_payload(&packet[1..])
    }
}
